export const TAGS: string[] = [
    "Sports",
    "Video Games",
    "DIY",
    "Music",
    "Movies",
    "Technology",
    "Travel",
    "Cooking",
    "Fitness",
    "Art",
    "Photography",
    "Books",
    "Fashion",
    "Health",
    "Education",
  ];